import './globals.css'
import Navbar from "@/components/navbar/Navbar";
import localFont from "next/font/local";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const lineSeed = localFont({
  src: [
    { path: "../../public/fonts/LINESeedSansTH_W_Rg.woff2", weight: "400", style: "normal" },
    { path: "../../public/fonts/LINESeedSansTH_W_Bd.woff2",    weight: "700", style: "normal" },
  ],
  variable: "--font-line-seed", // สร้าง CSS variable สำหรับอ้างใน CSS
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="th" className={lineSeed.variable}>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
